google.maps.api.key: QUl6YVN5Q055X3J4M2VIZFM0VG1CZU5FM1AxQm1Nc2JpcEszN2lj

server.port: 9797

spring:
  data:
    mongodb:
      name: route-cache
      uri: mongodb://localhost:27017/${spring.data.mongodb.name}?retryWrites=true&w=majority
